# Generated by Django 3.2.3 on 2021-05-24 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_simplerating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality', models.FloatField()),
                ('plot', models.FloatField()),
                ('cinematography', models.FloatField()),
                ('music_score', models.FloatField()),
                ('characters', models.FloatField()),
                ('entertainment_value', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
